### PR TITLE
Updates to include new python package versions and JSON configuration

### PR DESCRIPTION
**Pull request by thofsaw**
See changes. I had hoped to include .toml support but haven't figured that out yet.
Now uses more recent versions of packages that are no longer available and different CLI option support.
Added JSON configuration so that eaiser to configure for your own system.

### CODE REVIEW

**Comment by yuroller** [comment]
Actually I am still using this python script for my Aurora inverter on an openwrt router: have you tried it?
I was (months/years ago?) thinking to replace with a complete python solution.

**Comment by thofsaw** [comment]
Interesting! I am running on ubuntu server 20.04 LTS. Finally connected my aurora after about 10years (!). I had difficulty getting the libraries required to get it working (I think httplib in particular?) and thought I'd do a "tech refresh" and add a feature or two.
I had wondered what it might take to do a 'native' python solution.  I haven't looked into it.

**Comment by yuroller** [comment]
Take a look at https://github.com/gjr80/weewx-aurora
It is a full python implementation of aurora protocol inverter for the weewx platform: maybe the core protocol could be extracted and integrated into this or your repository.

**Comment by thofsaw** [comment]
Thanks for the link, but I suspect I won't be looking into it now that I have this up and working.

**Comment by yuroller** [comment]
Port to python3 and general code refresh (thanks @thofsaw)

**Pull request merged**
